# Generated by Django 2.0.1 on 2018-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website_rank',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_score',
            field=models.IntegerField(default=5),
        ),
    ]
