# Generated by Django 2.0.1 on 2018-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180406_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
