# Generated by Django 2.0.1 on 2018-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180420_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_likes',
            field=models.IntegerField(default=0),
        ),
    ]
