# Generated by Django 2.0.1 on 2018-06-01 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20180531_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_likes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_likes',
            field=models.ManyToManyField(default=False, related_name='profile_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
