# Generated by Django 2.0.1 on 2018-06-05 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180601_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_likes',
            field=models.ManyToManyField(blank=True, related_name='profile_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
