# Generated by Django 2.0.1 on 2018-06-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180614_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
