# Generated by Django 2.0.1 on 2018-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180614_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
