# Generated by Django 2.0.1 on 2018-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180615_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='profile_photo'),
        ),
    ]
