# Generated by Django 2.0.1 on 2018-06-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180621_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='maxdefaultres.jpg', upload_to='profile_photo'),
        ),
    ]
