# Generated by Django 2.0.1 on 2018-08-22 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0028_usergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
