# Generated by Django 2.0.1 on 2018-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.CharField(blank=True, default='No Notifications', max_length=100, null=True),
        ),
    ]
