# Generated by Django 2.0.1 on 2018-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180822_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='request_message',
            field=models.CharField(default='Wants to be friends with you', max_length=100),
        ),
    ]
