# Generated by Django 2.0.1 on 2018-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180823_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request_accept',
            field=models.BooleanField(default=True),
        ),
    ]
