# Generated by Django 2.0.1 on 2018-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(null=True, upload_to='media/photo_posts/'),
        ),
    ]
