# Generated by Django 2.0.1 on 2018-07-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_image_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_post',
            new_name='image',
        ),
    ]
