# Generated by Django 2.0.1 on 2018-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_friend_request_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request_message',
        ),
        migrations.AddField(
            model_name='friend',
            name='request_accept',
            field=models.BooleanField(default=False),
        ),
    ]
